Use [DEV-AHPLHRMS-US-Blank]
ALTER DATABASE [DEV-AHPLHRMS-US-Blank] SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKFILE('AHPLHRMS_log', 1)
ALTER DATABASE [DEV-AHPLHRMS-US-Blank] SET RECOVERY FULL WITH NO_WAIT
GO